version: 0.2
phases:
    build:
        commands:
        - docker run -it owasp/zap2docker-stable:latest /bin/bash -c "pip install wait-for-it"
        - zaproxy -version
        - zaproxy -cmd -quickurl https://google.com -quickprogress -quickout ~/result.json
    post_build:
        commands:
        - echo "DAST Results"
        - cat result.json
        #- echo $result | jq . 
        - echo Build completed
