version: 0.2
phases:
    build:
        commands:
        - apt update
        - apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - apt install docker-ce -y
        - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
        - curl https://bootstrap.pypa.io/get-pip.py | python3
        - echo Starting OWASP Zed Attack Proxy active scanning...
        - chmod 777 $PWD
        - mkdir -p /zap/wrk
        - chmod 777 /zap/wrk      
        - docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-weekly zap-baseline.py -t https://ugagcfitjh.execute-api.us-east-1.amazonaws.com/dev/hello -c passive-scan.conf -J owaspresult.json 
        - echo Build completed
