version: 0.2
run-as: root

phases:
    build:
        commands:
        - iwr -useb get.scoop.sh | iex
        - scoop install zaproxy
        - zaproxy -version
        - zaproxy -cmd -quickurl https://google.com -quickprogress -quickout ~/result.json
    post_build:
        commands:
        - echo "DAST Results"
        - cat result.json
        #- echo $result | jq . 
        - echo Build completed
