version: 0.2

phases:
    build:
        commands:
        - echo "Build started"
        - echo "installing OWASP..." 
        - sudo apt update
        - sudo apt install snapd
        - snap install zaproxy --classic
        - zaproxy -version
        - zaproxy -cmd -quickurl https://google.com -quickprogress -quickout ~/result.json
    post_build:
        commands:
        - echo "DAST Results"
        - cat result.json
        #- echo $result | jq . 
        - echo Build completed
